version: '2'

services:
  auto-tests:
   environment:
        HTTP_CREDENTIALS_USERNAME: ${HTTP_CREDENTIALS_USERNAME}
        HTTP_CREDENTIALS_PASSWORD: ${HTTP_CREDENTIALS_PASSWORD}
  container_name: "automated-tests"
  build:
    context: .